services:
  - type: web
    name: audiohub
    runtime: node
    buildCommand: cd backend && npm install --ignore-scripts && npx prisma generate && npx tsc -p tsconfig.json
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_PRISMA_MIGRATE
        value: "true"
